---
parser: babel-eslint

plugins:
  - react
  - jest
  - prettier
  - babel
  - react-hooks

extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  no-console: 0
  react/jsx-filename-extension: 0
  react/prop-types: 0
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
